import type { Metadata } from "next";
import { Noto_Sans_JP } from "next/font/google";
import TanstacksProvider from "@/app/TanstacksProvider";
import "./globals.css";

const notoSansJP = Noto_Sans_JP({
  variable: "--font-noto-sans-jp",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${notoSansJP.variable} ${notoSansJP.className} antialiased`}
      >
        <TanstacksProvider>
          {children}
        </TanstacksProvider>
      </body>
    </html>
  );
}
